# Generated by Django 5.1.6 on 2025-02-13 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("iata_code", models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Airport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("iata_code", models.CharField(max_length=3, unique=True)),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flight_number", models.CharField(max_length=10)),
                ("scheduled_departure", models.DateTimeField()),
                ("actual_departure", models.DateTimeField(blank=True, null=True)),
                ("scheduled_arrival", models.DateTimeField()),
                ("actual_arrival", models.DateTimeField(blank=True, null=True)),
                (
                    "airline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="agoa.airline"
                    ),
                ),
                (
                    "arrival_airport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arrivals",
                        to="agoa.airport",
                    ),
                ),
                (
                    "departure_airport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departures",
                        to="agoa.airport",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("flight_number", "airline", "scheduled_departure")
                },
            },
        ),
        migrations.CreateModel(
            name="Turnaround",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_start", models.DateTimeField()),
                ("actual_start", models.DateTimeField(blank=True, null=True)),
                ("scheduled_end", models.DateTimeField()),
                ("actual_end", models.DateTimeField(blank=True, null=True)),
                (
                    "airport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="agoa.airport"
                    ),
                ),
                (
                    "arrival_flight",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arrival_turnaround",
                        to="agoa.flight",
                    ),
                ),
                (
                    "departure_flight",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departure_turnaround",
                        to="agoa.flight",
                    ),
                ),
            ],
        ),
    ]
