# Generated by Django 5.1.6 on 2025-02-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agoa", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="airport",
            name="latitude",
            field=models.FloatField(default=48.85),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="airport",
            name="longitude",
            field=models.FloatField(default=2.35),
            preserve_default=False,
        ),
    ]
