name: CI

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: 3.12

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Cache Poetry virtualenv
        uses: actions/cache@v3
        id: cache
        with:
            path: ~/.virtualenvs
            key: poetry-${{ hashFiles('**/poetry.lock') }}
            restore-keys: |
                poetry-${{ hashFiles('**/poetry.lock') }}
      - name: Configure Poetry
        run: |
          poetry config virtualenvs.in-project true
          poetry config virtualenvs.path ~/.virtualenvs

      - name: Install Dependencies
        run: poetry install
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Code Quality
        run: poetry run black . --check
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV  # Set the PYTHONPATH to the current directory

      - name: Test with pytest
        env:
          DJANGO_SETTINGS_MODULE: agoa.settings
          SECRETS_FILE: .confidential/ci.json
        run: poetry run pytest --cov . -n 2

      - name: Type checking
        env:
          DJANGO_SETTINGS_MODULE: "agoa.settings"
          PYTHONPATH: ${{ github.workspace }}
        run: poetry run mypy agoa authentication --ignore-missing-imports
        continue-on-error: true
